apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
resources:
  - namespace.yaml
  - resources.yaml

configMapGenerator:
  - name: example-chart-values
    files:
      - values.yaml=configs/example-chart-values.yaml
