apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
resources:
  - namespace.yaml
  - resources.yaml

configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  - name: example-chart-values
    files:
      - values.yaml=configs/example-chart-values.yaml
  - name: example-chart-overlay-values
    files:
      - values.yaml=configs/example-chart-overlay-values.yaml

patchesStrategicMerge:
  - patch-release.yaml
