apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example-chart-release
  namespace: example
spec:
  valuesFrom:
    # base values
    - name: example-chart-values
      kind: ConfigMap
    # overlay values
    - name: example-chart-overlay-values
      kind: ConfigMap