apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config-map
data:
  problem: "an example of a multi-line string \ string\\with\\backslashes and a\n
    \    substitution: ${example} and a literal $${<-- dollar sign}"