apiVersion: v1
kind: ConfigMap
metadata:
  name: nested-chart-config-map
data:
  control: |
    This should work {{ .Values.config.test }}
  test: |
    This should also work, but it breaks {{ .Values.config.problem }}